apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-prod

resources:
  - ../../base

images:
  - name: weather-api
    newName: PLACEHOLDER_ECR_URL
    newTag: prod-latest

patches:
  - path: serviceaccount-patch.yaml
    target:
      kind: ServiceAccount
      name: weather-api
  - path: externalsecret-patch.yaml
    target:
      kind: ExternalSecret
      name: weather-app-config
  - path: scaledobject-patch.yaml
    target:
      kind: ScaledObject
      name: weather-api
  - path: deployment-replicas-patch.yaml
    target:
      kind: Deployment
      name: weather-api
