apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-db-cache
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: trivy-db-cache
    app.kubernetes.io/managed-by: terraform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-default-sc
  resources:
    requests:
      storage: 8Gi
