apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-staging

resources:
  - namespace.yaml
  - ../../base

images:
  - name: weather-api
    newName: 339712707744.dkr.ecr.us-east-1.amazonaws.com/poc-max-weather-api-repo
    newTag: 679a91b-fetchfix
